<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Traits\CreatedUpdatedBy;

class Port extends Model
{
    use SoftDeletes, CreatedUpdatedBy;

    protected $fillable = [
        'name',
        'country',
        'geojson',
        'geom',
        'index_no',
        'region_no',
        'latitude',
        'longitude',
        'lat_deg',
        'lat_min',
        'lat_hemi',
        'long_deg',
        'long_min',
        'long_hemi',
        'pub',
        'chart',
        'harborsize',
        'harbortype',
        'shelter',
        'entry_tide',
        'entryswell',
        'entry_ice',
        'entryother',
        'overhd_lim',
        'chan_depth',
        'anch_depth',
        'cargodepth',
        'oil_depth',
        'tide_range',
        'max_vessel',
        'holdground',
        'turn_basin',
        'portofentr',
        'us_rep',
        'eta_message',
        'pilot_reqd',
        'pilotavail',
        'loc_assist',
        'pilotadvsd',
        'tugsalvage',
        'tug_assist',
        'pratique',
        'sscc_cert',
        'quar_other',
        'comm_phone',
        'comm_fax',
        'comm_radio',
        'comm_vhf',
        'comm_air',
        'comm_rail',
        'cargowharf',
        'cargo_anch',
        'cargmdmoor',
        'carbchmoor',
        'caricemoor',
        'med_facil',
        'garbage',
        'degauss',
        'drtyballst',
        'cranefixed',
        'cranemobil',
        'cranefloat',
        'lift_100',
        'lift50_100',
        'lift_25_49',
        'lift_0_24',
        'longshore',
        'electrical',
        'serv_steam',
        'nav_equip',
        'elecrepair',
        'provisions',
        'water',
        'fuel_oil',
        'diesel',
        'deck_supply',
        'eng_supply',
        'repaircode',
        'drydock',
        'railway',
        'created_by',
        'updated_by',
        'deleted_by',
    ];
}
